### ISSUE TITLE
as a developer I want to make sure we don't  add multiple no-value statements but instead add another point in time qualifier to the current no-value statement 

### ISSUE THREAD

**Issue by dpriskorn** [dpriskorn/hiking_trail_matcher#16]

**Comment by salgo60** [comment]
@dpriskorn  What is the user case of no value?

I can see
1. We have a source that indictes this poerson has no value e.g. not being maried, not beeing part of a party
1. ???

**Comment by dpriskorn** [comment]
The use case is for the tool. Someone reviewed it at least once and found no match in OSM.

**Comment by dpriskorn** [comment]
fixed by changing the model
